# Pandas (Series)

In [1]:
# Why Pandas? 

# Pandas is a powerful and flexible open-source data analysis and manipulation library for Python. 

# It provides data structures like DataFrames and Series that make it easy to work with structured data. 

# Here are some reasons why Pandas is widely used:  
# 01. Easy to use.
# 02. Efficient: Pandas is built on top of NumPy - fast and efficient data processing, even with large datasets.
# 03. Versatile: Pandas can handle a wide variety of data formats, including CSV, Excel, SQL databases, etc.
# 04. Integration: Pandas integrates well with other Python libraries, such as Matplotlib, Scikit-learn.
# 05. Community support
# 06. Data Cleaning: 
#      - Pandas provides robust tools for cleaning and preparing data, including:
#           1. handling missing values
#           2. handling duplicates
#           3. handling inconsistent data types

# 07. Data Transformation: Pandas allows for easy reshaping and pivoting of data
# 08. Performance: Pandas is optimized for performance, allowing for efficient data manipulation and analysis
# 09. Visualization: Pandas has built-in support for basic data visualization
# 10. Documentation: Pandas has comprehensive documentation and tutorials
# 11. Pandas is open-source software
# 12. Data Alignment: Pandas automatically aligns data for you when performing operations on different datasets
# 13. Time Series Analysis: Pandas provides specialized functionality for working with time series data
# 14. Grouping and Aggregation: Pandas makes it easy to group data by one or more keys and perform aggregate functions
# 15. Extensibility: Pandas can be extended with custom functions and methods

In [2]:
# always import pandas and numpy at the beginning of your script

import numpy as np
import pandas as pd

In [3]:
# What is Series? 

# A Series is a 1D labeled array capable of holding any data type (integers, strings, float, Python objects, etc.).
# The labels, also known as the index, allow for easy access and manipulation of data.  

# We can create a Series from a list, NumPy array, or dictionary.

In [4]:
# Series of strings

countries = ['Pakistan', 'India', 'Bangladesh','Afghanistan', 'Nepal', 'Sri Lanka', 'Bhutan', 'Maldives']   

pd.Series(countries)

# Series is a class inside Pandas library. 
# We can create a Series object by calling the Series class and passing in the data we want to store in the Series.

0       Pakistan
1          India
2     Bangladesh
3    Afghanistan
4          Nepal
5      Sri Lanka
6         Bhutan
7       Maldives
dtype: str

In [5]:
# Series of integers

runs_Kohli = [183, 160, 122, 97, 82, 70, 65, 55]

pd.Series(runs_Kohli)

0    183
1    160
2    122
3     97
4     82
5     70
6     65
7     55
dtype: int64

In [6]:
# Custom index instead of 0,1,2,3,4,5,6,7

marks_Arsalan = [85, 90, 78, 92, 88]
subjects = ['Math', 'Science', 'English', 'History', 'Geography']

pd.Series(marks_Arsalan, index=subjects)

Math         85
Science      90
English      78
History      92
Geography    88
dtype: int64

In [7]:
marks_series = pd.Series(marks_Arsalan, index=subjects, name='Arsalan ke Marks')

marks_series
# the name is like a title or ID for the Series. 
# It can be useful when working with multiple Series or when displaying the data in a DataFrame.

Math         85
Science      90
English      78
History      92
Geography    88
Name: Arsalan ke Marks, dtype: int64

In [8]:
# Series from dictionary

marks_dict = {
    'Math': 85,
    'Science' : 90,
    'English' : 78,
    'History' : 92,
    'Geography' : 88
}

marks_dict

{'Math': 85, 'Science': 90, 'English': 78, 'History': 92, 'Geography': 88}

# Series Attributes

In [9]:


# size of a series

marks_series.size

5

In [10]:
# data type of a series

marks_series.dtype

dtype('int64')

In [11]:
# name of a series

marks_series.name

'Arsalan ke Marks'

In [12]:
# is_unique

# this will show if all the values in the series are unique or not. 
# It will return True if all values are unique, otherwise it will return False.

marks_series.is_unique

True

In [13]:
# I just want to check whether the is_unique attribute is working or not. 
# So, I will create a new list with some duplicate values and then create a new Series from that list.

marks_new = [20, 15 ,20, 50, 95, 80]
subjects_new = ['Math', 'Science', 'English', 'History', 'Geography', 'Math']

marks_series_new = pd.Series(marks_new, index = subjects_new, name='Marks with Duplicates')
marks_series_new

Math         20
Science      15
English      20
History      50
Geography    95
Math         80
Name: Marks with Duplicates, dtype: int64

In [14]:
marks_series_new.is_unique

False

In [15]:
# index items

marks_series.index

Index(['Math', 'Science', 'English', 'History', 'Geography'], dtype='str')

In [16]:
# values (instead of index)

marks_series.values

array([85, 90, 78, 92, 88])

# Series using read_csv 

(i.e. reading an existing data set)

In [17]:
# csv files mean Comma Separated Values files.
# In such files, data is stored in a tabular format.
# each row represents a record and each column represents a field (attribute).

# I have already downloaded the three csv files which the teacher have used in the video. You can download them from the following links:
# https://raw.githubusercontent.com/arsal3646/Python_Projects/main/CampusX_Data_Science_Course/016_DataSets_Pandas/subs.csv

subs = pd.read_csv('https://raw.githubusercontent.com/arsal3646/Python_Projects/main/CampusX_Data_Science_Course/016_DataSets_Pandas/subs.csv')

subs

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [18]:
# Note: the type of the above object is automatically a DataFrame, not a Series.

type(subs)

pandas.DataFrame

In [19]:
# we need to convert the DataFrame into a Series.
# this is done by using Squeeze method, i.e. squeeze = True

subs_series = subs.squeeze() 

# you can also doing the same directly while reading the csv file by using the squeeze parameter.
# the code would have been like this:
# subs_series = pd.read_csv('https://raw.githubusercontent.com/arsal3646/Python_Projects/main/CampusX_Data_Science_Course/016_DataSets_Pandas/subs.csv', squeeze=True)

subs_series

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [20]:
subs_series.name

# the name of the Series is automatically set to the name of the column in the DataFrame.

'Subscribers gained'

In [21]:
type(subs_series)

# now it is changed to a Series object from a DataFrame object.

pandas.Series

In [22]:
# Pandas Series - with one column

subs_series

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [23]:
import pandas as pd

urls = [
    "https://raw.githubusercontent.com/arsal3646/Python_Projects/main/CampusX_Data_Science_Course/016_DataSets_Pandas/kohli_ipl.csv",
    "https://raw.githubusercontent.com/arsal3646/Python_Projects/master/CampusX_Data_Science_Course/016_DataSets_Pandas/kohli_ipl.csv",
    "https://raw.githubusercontent.com/arsal3646/Python_Projects/main/CampusX_Data_Science_Course/016_DataSets_Pandas/kohli_runs.csv",
    "https://raw.githubusercontent.com/arsal3646/Python_Projects/master/CampusX_Data_Science_Course/016_DataSets_Pandas/kohli_runs.csv",
]

for url in urls:
    try:
        kohli = pd.read_csv(url, index_col="match_no").squeeze("columns")
        print("Loaded from:", url)
        break
    except Exception as e:
        print("Failed:", url)

kohli

Loaded from: https://raw.githubusercontent.com/arsal3646/Python_Projects/main/CampusX_Data_Science_Course/016_DataSets_Pandas/kohli_ipl.csv

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64

In [24]:
# now let us use kohli_runs.csv file to create a Series with 2 columns.

import pandas as pd

kohli = pd.read_csv(
    'https://raw.githubusercontent.com/arsal3646/Python_Projects/main/CampusX_Data_Science_Course/016_DataSets_Pandas/kohli_ipl.csv',
    index_col='match_no'
).squeeze('columns')

kohli

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64

In [25]:
bollywood = pd.read_csv(
    'https://raw.githubusercontent.com/arsal3646/Python_Projects/main/CampusX_Data_Science_Course/016_DataSets_Pandas/bollywood.csv'
)

bollywood

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

In [26]:
# Pandas Series -  with 2 columns  
 
bollywood_series = bollywood.squeeze('columns')

bollywood_series

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

# Series Methods

In [27]:
# head and tail methods

bollywood_series.head(3)  # this will show the first 3 rows of the Series

                                  movie           lead
0              Uri: The Surgical Strike  Vicky Kaushal
1                         Battalion 609    Vicky Ahuja
2  The Accidental Prime Minister (film)    Anupam Kher

In [28]:
kohli.head(3)  # this will show the first 3 rows of the Series

match_no
1     1
2    23
3    13
Name: runs, dtype: int64

In [29]:
kohli.tail(10)  # this will show the last 10 rows of the Series

match_no
206     0
207     0
208     9
209    58
210    30
211     0
212    20
213    73
214    25
215     7
Name: runs, dtype: int64

In [30]:
bollywood_series.tail(8)  # this will show the last 8 rows of the Series

                           movie              lead
1492  Waisa Bhi Hota Hai Part II      Arshad Warsi
1493    Devdas (2002 Hindi film)    Shah Rukh Khan
1494                      Kaante  Amitabh Bachchan
1495      Hum Tumhare Hain Sanam    Shah Rukh Khan
1496         Aankhen (2002 film)  Amitabh Bachchan
1497             Saathiya (film)      Vivek Oberoi
1498              Company (film)        Ajay Devgn
1499        Awara Paagal Deewana      Akshay Kumar

In [31]:
# sample method shows a random sample of rows from the Series.

kohli.sample()

match_no
108    48
Name: runs, dtype: int64

In [32]:
bollywood_series.sample(10)  # this will show a random sample of 10 rows from the Series

                                               movie                lead
494                                     Koyelaanchal  Kannan Arunachalam
548                       Happy New Year (2014 film)      Shah Rukh Khan
1061               Blood Brothers (2007 Indian film)           Jazzy Doe
339                                    Beiimaan Love         Sunny Leone
267                                     Ishq Forever  Krishna Chaturvedi
369                           Mumbai Can Dance Saala       Shakti Kapoor
406                                    Bombay Velvet       Ranbir Kapoor
1375  Netaji Subhas Chandra Bose: The Forgotten Hero         Vinay Anand
1469                             Parwana (2003 film)          Ajay Devgn
467                        Highway (2014 Hindi film)          Alia Bhatt

In [33]:
# value counts (based on lead as the Series has 2 columns.
# we can specify the column name to get the value counts for that column.

bollywood_series['lead'].value_counts()

# this is like countif() in Excel.

lead
Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
                    ..
Tanishaa Mukerji     1
Tanuja               1
Ankit                1
Rakhee Gulzar        1
Edwin Fernandes      1
Name: count, Length: 566, dtype: int64

In [34]:
# sort_values method sorts the values in the Series in ascending order by default.

# if we use the parameter ascending=False, it will sort the values in descending order.

bollywood['lead'].value_counts().sort_values(ascending=True)

lead
Saurav Chakraborty     1
Elisha Kriis           1
Chandan Roy Sanyal     1
Tinnu Anand            1
Sumit Nijhawan         1
                      ..
Sanjay Dutt           26
Salman Khan           31
Ajay Devgn            38
Amitabh Bachchan      45
Akshay Kumar          48
Name: count, Length: 566, dtype: int64

In [35]:
# How to find the highest and lowest values in a Series?

bollywood['lead'].value_counts().sort_values(ascending=False).head(1)  # this will show the highest value in the Series

lead
Akshay Kumar    48
Name: count, dtype: int64

In [36]:
bollywood['lead'].value_counts().sort_values(ascending=True).head(1)  # this will show the lowest value in the Series

# This is is called method chaining. It is a way to call multiple methods on an object in a single line of code.
# Method chaining can make the code more concise and readable 
# but it can also make it harder to debug if something goes wrong.

lead
Saurav Chakraborty    1
Name: count, dtype: int64

In [37]:
# inplace parameter is used to modify the "original" Series instead of creating a new one.

# inplace = True means that the original Series will be modified and the changes will be saved in the same Series object.

In [38]:
bollywood_series.count()  # this will show the number of non-null values in the Series

movie    1500
lead     1500
dtype: int64

In [39]:
subs_series.count()  # this will show the number of non-null values in the Series

np.int64(365)

In [40]:
subs_series.sum()

np.int64(49510)

In [41]:
subs_series.mean()  # this will show the mean of the values in the Series.

# on a daily basis, he is getting 135 new subscribers on his YouTube channel.

np.float64(135.64383561643837)

In [42]:
subs_series.median()  # this will show the median of the values in the Series

np.float64(123.0)

In [43]:
bollywood_series.mode() # this will show the mode of the values in the Series

                     movie          lead
0                   Andaaz  Akshay Kumar
1           Gabbar Is Back           NaN
2  Tanu Weds Manu: Returns           NaN

In [44]:
subs_series.std()  # this will show the standard deviation of the values in the Series

np.float64(62.6750230372527)

In [45]:
subs_series.var()  # this will show the variance of the values in the Series

np.float64(3928.1585127201565)

In [46]:
subs_series.min()  # this will show the minimum value in the Series

np.int64(33)

In [47]:
subs_series.max()

np.int64(396)

In [48]:
subs_series.describe()  # this will show the summary statistics of the values in the Series

count    365.000000
mean     135.643836
std       62.675023
min       33.000000
25%       88.000000
50%      123.000000
75%      177.000000
max      396.000000
Name: Subscribers gained, dtype: float64

In [52]:
bollywood_series.describe()  # this will show the summary statistics of the values in the Series

                          movie          lead
count                      1500          1500
unique                     1497           566
top     Tanu Weds Manu: Returns  Akshay Kumar
freq                          2            48

In [51]:
kohli.describe()  # this will show the summary statistics of the values in the Series

count    215.000000
mean      30.855814
std       26.229801
min        0.000000
25%        9.000000
50%       24.000000
75%       48.000000
max      113.000000
Name: runs, dtype: float64

In [53]:
# slicing in Pandas

# It is similar to slicing in Python lists and NumPy arrays.

kohli[0:5]  # this will show the first 5 rows of the Series

match_no
1     1
2    23
3    13
4    12
5     1
Name: runs, dtype: int64

In [55]:
kohli[5:10]  # this will show the rows from index 5 to 9 of the Series. It will not include the row at index 10.

match_no
6      9
7     34
8      0
9     21
10     3
Name: runs, dtype: int64

In [56]:
# check last five rows of the Series

bollywood_series[-5:]  # this will show the last 5 rows of the Series

                       movie              lead
1495  Hum Tumhare Hain Sanam    Shah Rukh Khan
1496     Aankhen (2002 film)  Amitabh Bachchan
1497         Saathiya (film)      Vivek Oberoi
1498          Company (film)        Ajay Devgn
1499    Awara Paagal Deewana      Akshay Kumar

In [59]:
# fancy indexing in Pandas

# fancy indexing is a way to select specific rows from a Series using a list of indices rather than using a range of indices or a pattern.

kohli[[1, 2, 4]]  # this will show the rows at index 1, 2, and 4 of the Series

match_no
1     1
2    23
4    12
Name: runs, dtype: int64

In [61]:
# Series with Python Functionalities

# You can use Python's built-in functions and methods on Pandas Series.
# For example, you can use len(), min(), max(), sum(), and other functions.

len(kohli)  # this will return the number of elements in the Series

215

In [62]:
min(kohli)  # this will return the minimum value in the Series

0

In [63]:
max(kohli)  # this will return the maximum value in the Series

113

In [64]:
sum(kohli)  # this will return the sum of all values in the Series

6634

In [66]:
type(subs)

pandas.DataFrame

In [67]:
type(subs_series)

pandas.Series

In [69]:
# See list of all available methods and attributes of a Series object.

# You can use the dir() function to see a list of all available methods and attributes of a Series object.

dir(subs_series)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__firstlineno__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append_internal',
 '_arith_method',
 '_attrs',
 '_binop',
 '_can_hold_na',
 '_check_copy_deprecation',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_label_or_level_ambiguity',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_expanddim_from_mgr',
 '_constructor_from_mgr',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_duplicated',
 '_find_valid_index',
 '_flags',
 '_flex_method',
 '_from_mgr',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_index_resolvers',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_rows_with_mask',
 '_get_value',
 '_get_values_tuple',
 '_get_with',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_init_dict',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_map_values',
 '_memory_usage',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_module_source',
 '_name',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_reduce',
 '_references',
 '_reindex_axes',
 '_reindex_indexer',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_repr_data_resource_',
 '_repr_latex_',
 '_reset_cache',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_labels',
 '_set_name',
 '_set_value',
 '_set_values',
 '_set_with',
 '_set_with_engine',
 '_shift_with_freq',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'argmax',
 'argmin',
 'argsort',
 'array',
 'asfreq',
 'asof',
 'astype',
 'at',
 'at_time',
 'attrs',
 'autocorr',
 'axes',
 'between',
 'between_time',
 'bfill',
 'case_when',
 'clip',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'divmod',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtype',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'ewm',
 'expanding',
 'explode',
 'factorize',
 'ffill',
 'fillna',
 'filter',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_arrow',
 'ge',
 'get',
 'groupby',
 'gt',
 'hasnans',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'interpolate',
 'is_monotonic_decreasing',
 'is_monotonic_increasing',
 'is_unique',
 'isin',
 'isna',
 'isnull',
 'item',
 'items',
 'keys',
 'kurt',
 'kurtosis',
 'last_valid_index',
 'le',
 'list',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'memory_usage',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'name',
 'nbytes',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'radd',
 'rank',
 'rdiv',
 'rdivmod',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'repeat',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'searchsorted',
 'sem',
 'set_axis',
 'set_flags',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'std',
 'struct',
 'sub',
 'subtract',
 'sum',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_frame',
 'to_hdf',
 'to_json',
 'to_latex',
 'to_list',
 'to_markdown',
 'to_numpy',
 'to_period',
 'to_pickle',
 'to_sql',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unique',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

In [72]:
sorted(subs_series) # this will return a sorted list of all values in the Series

# the output is a LIST.

[33,
 33,
 35,
 37,
 39,
 40,
 40,
 40,
 40,
 42,
 42,
 43,
 44,
 44,
 44,
 45,
 46,
 46,
 48,
 49,
 49,
 49,
 49,
 50,
 50,
 50,
 51,
 54,
 56,
 56,
 56,
 56,
 57,
 61,
 62,
 64,
 65,
 65,
 66,
 66,
 66,
 66,
 67,
 68,
 70,
 70,
 70,
 71,
 71,
 72,
 72,
 72,
 72,
 72,
 73,
 74,
 74,
 75,
 76,
 76,
 76,
 76,
 77,
 77,
 78,
 78,
 78,
 79,
 79,
 80,
 80,
 80,
 81,
 81,
 82,
 82,
 83,
 83,
 83,
 84,
 84,
 84,
 85,
 86,
 86,
 86,
 87,
 87,
 87,
 87,
 88,
 88,
 88,
 88,
 88,
 89,
 89,
 89,
 90,
 90,
 90,
 90,
 91,
 92,
 92,
 92,
 93,
 93,
 93,
 93,
 95,
 95,
 96,
 96,
 96,
 96,
 97,
 97,
 98,
 98,
 99,
 99,
 100,
 100,
 100,
 101,
 101,
 101,
 102,
 102,
 103,
 103,
 104,
 104,
 104,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 105,
 108,
 108,
 108,
 108,
 108,
 108,
 109,
 109,
 110,
 110,
 110,
 111,
 111,
 112,
 113,
 113,
 113,
 114,
 114,
 114,
 114,
 115,
 115,
 115,
 115,
 117,
 117,
 117,
 118,
 118,
 119,
 119,
 119,
 119,
 120,
 122,
 123,
 123,
 123,
 123,
 123,
 124,
 125,
 126,
 127,
 128,
 128,
 129,
 130,
 131,
 131,
 132,
 132,
 134,
 134,
 134,
 135,
 135,
 136,
 136,
 136,
 137,
 138,
 138,
 138,
 139,
 140,
 144,
 145,
 146,
 146,
 146,
 146,
 147,
 149,
 150,
 150,
 150,
 150,
 151,
 152,
 152,
 152,
 153,
 153,
 153,
 154,
 154,
 154,
 155,
 155,
 156,
 156,
 156,
 156,
 157,
 157,
 157,
 157,
 158,
 158,
 159,
 159,
 160,
 160,
 160,
 160,
 162,
 164,
 166,
 167,
 167,
 168,
 170,
 170,
 170,
 170,
 171,
 172,
 172,
 173,
 173,
 173,
 174,
 174,
 175,
 175,
 176,
 176,
 177,
 178,
 179,
 179,
 180,
 180,
 180,
 182,
 183,
 183,
 183,
 184,
 184,
 184,
 185,
 185,
 185,
 185,
 186,
 186,
 186,
 188,
 189,
 190,
 190,
 192,
 192,
 192,
 196,
 196,
 196,
 197,
 197,
 202,
 202,
 202,
 203,
 204,
 206,
 207,
 209,
 210,
 210,
 211,
 212,
 213,
 214,
 216,
 219,
 220,
 221,
 221,
 222,
 222,
 224,
 225,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 233,
 236,
 236,
 237,
 241,
 243,
 244,
 245,
 247,
 249,
 254,
 254,
 258,
 259,
 259,
 261,
 261,
 265,
 267,
 268,
 269,
 276,
 276,
 290,
 295,
 301,
 306,
 312,
 396]

Studied until min 1 hour 40 min